{{- if .Values.deploy.applicationProperties.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarkus.name" . }}
  labels:
    {{- include "quarkus.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "config/**").AsConfig | indent 2 }} 
{{- end }}

